### ISSUE TITLE
Can2IP Wrapper 

### ISSUE THREAD

**Issue by charif-mahmoudi** [usnistgov/Intra-Vehicular-Networks#2]
1. client server over IP
2. read can traffic and integrate it to the client
2. write can traffic received by the server

**Comment by KhalidHALBA-GR-NIST** [comment]
Pi1 : 

- send an e-mail to the can-utils mailing list : 	linux-can@vger.kernel.org and ask whether they have a lightweight application that receives the can traffic. (as can-dump is heavy and has extra functionalities that we do not need at this level)  

Pi2: 

- Integrate can-send with the server code.
  can-send code : https://github.com/linux-can/can-utils/blob/master/cansend.c
-  using the product of this integration (can2IP wrapper) to Send can traffic to vcan0 
- Check if traffic is coming with can-dump utility on vcan0.

**Comment by KhalidHALBA-GR-NIST** [comment]
to run the CAN2IPWRAPPER use the following command :  
./can2IPwrapper -L -h 192.168.1.2
